#!/bin/bash

echo "================Starting security update================"

# Output directory
output_dir="/opt/security_update"
output_file="$output_dir/security_update_output.txt"

# Create the output directory if it doesn't exist
sudo mkdir -p "$output_dir"
sudo chmod 777 "$output_dir" 

# Update the package repositories and install security updates
if sudo yum -y update --security; then
  echo "Security updates applied successfully." > "$output_file"
else
  echo "Failed to apply security updates. Please check the logs for more information." > "$output_file"
  exit 1
fi
